# Header Menu
menu:
  Home: /
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
  About: /about/
   
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: saboloh
google_analytics:
#swiftype_install_key: BfzEd9hi5iLwB5Qdn3iV
google_api: AIzaSyCLiGs8uqSbzACaM0oG3wAyKHuDPkzxz_E

# Social
social:
  github: https://github.com/jianle
  twitter: 
  facebook: 
  rss: atom.xml
  linkedin: 
  stackoverflow: 

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise,black
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "678830341331820544" # as a string, from https://twitter.com/settings/widgets
twitter_username: computerlab_ # twitter username without the @
default_author: Anonymous

about: Computer Lab is a software development and marketing company based in Brooklyn, New York. <br><br> Computer Lab was founded in 2015, and is focused on so on and so forth.
phone: 
email: saboloh@163.com
address_1: China
address_2: ShangHai
address_3: Pudong New District, 1217
skype: saboloh
lat: 31.2173582
long: 121.5295839
